### ISSUE TITLE
Error when renaming files with special chars

### ISSUE THREAD

**Issue by gibaBR** [gibaBR/Switch-Backup-Manager#1]
found a small bug... if the game title has a colon ":" in it, it will throw up an error when renaming

**Comment by lorddusk** [comment]
To be exact this error :

> ************** Exception Text **************
> System.NotSupportedException: The given path's format is not supported.
>    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
>    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
>    at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
>    at Switch_Backup_Manager.Util.AutoRenameXCIFile(FileData file)
>    at Switch_Backup_Manager.Util.AutoRenameXCIFiles(Dictionary`2 files, String source)
>    at Switch_Backup_Manager.FrmMain.OperationRenameSelectedSDCardFiles()
>    at Switch_Backup_Manager.FrmMain.autoRenameFilesToolStripMenuItemRenameSD_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by gibaBR** [comment]
Solved on commit d71ba0d.
Will be released on v1.0.1
