### ISSUE TITLE
Stopping the scan when found a custom xci package

### ISSUE THREAD

**Issue by UNREALWINS** [gibaBR/Switch-Backup-Manager#104]
I have a lot a custom xci packages in my xci directory, but when the SBM scans the directory and found one custom xci the scan stop. 

Example: I have "Rocket League + DLC + Updates.xci". When The SBM scan and this game is found the scan stops. Then, the nexts games (alphabetic order) don't be scanned anymore.

Please, fix it. If SMB found a custom game, then add the game or simply ignore. Or ask.

**Comment by Kyosfonica** [comment]
I had the same issue. Some XCI just stoped the scan with an error.

Check you have the latests hacktool version and the lastest keys too.

The issue in my case was that some games required a higher key than the ones on my keys text file.
After adding them, the issue was gone.

**Comment by garoxas** [comment]
please this build and see if it fixes the issue https://mega.nz/#!FcVxFAzQ!IqsuKzFFbvtP0euQwHPyMBRW0fs1NsAPb3hmNHvTD7s
