### ISSUE TITLE
Possible to grab latest DLC version like other types of files?

### ISSUE THREAD

**Issue by deadair3210** [gibaBR/Switch-Backup-Manager#109]
Currently, DLC's do not have anything listed as their latest version, even though DLC nsp packages do utilize versioning just like updates. Easiest example that comes to mind is some of the Xenoblade Chronicles 2 DLC that has been updated as they add more dlc

**Comment by garoxas** [comment]
currently the method that we used to get latest version use the tagaya server which is more lenient where even some banned certs can still be used, but the drawback is no DLC versions
if we're to change it to use superfly server where we can also have DLC version, most users won't be able to use it anyway and end up rely on the cached list all the time (where I'm a little behind to update it regularly)

**Comment by garoxas** [comment]
not without breaking the download directly from nintendo server method

**Comment by deadair3210** [comment]
Ok thanks anyway

**Comment by deadair3210** [comment]
Ok thanks anyway
