### ISSUE TITLE
É in POKKÉN TOURNAMENT Not Readable by SXOS

### ISSUE THREAD

**Issue by adh1310** [gibaBR/Switch-Backup-Manager#11]
Hello and thank you for the hard work! Just wanted to give you a heads up, SXOS doesn't seem to like the É in POKKÉN TOURNAMENT, so you may want to add that to the list of disallowed special characters.

Thanks for the hard work!

**Comment by gibaBR** [comment]
Thank you very much. Version 1.0.6 will resolve this problem!

**Comment by gibaBR** [comment]
Actually version 1.0.7
