### ISSUE TITLE
[REQUEST] Change Scene Release Source

### ISSUE THREAD

**Issue by zebualvi** [gibaBR/Switch-Backup-Manager#114]
Hi there, it seems that NSWDB has stopped updating Scene List. Would it be possible to change the source to https://switchbrew.org/wiki/Title_list/Games? 

Thanks.

**Comment by garoxas** [comment]
That's no scene release though, it's just collection of title id, name and versions
I kinda forget but I think we used to have no-intro scene releases list but couldn't find it everywhere

Closest we can use now is http://rom-news.org/nsw as it has nfo for each releases, but no easy way to get them all (need to parse each pages and download every nfos)

**Comment by garoxas** [comment]
their discord is still active and they're planning to update it after holiday break

<img width="693" alt="nswdb" src="https://user-images.githubusercontent.com/11901820/50720374-aa73a300-10de-11e9-9a5f-f7d10931f623.PNG">

so I'd say we stick with nswdb for now
although I've also contacted the owner of https://twitter.com/JJBot4 and asked him how it works, just in case nswdb is not updated so we can have alternate solution

I think we can close this issue and reopen it if there's really no update from nswdb

**Comment by zebualvi** [comment]
Thanks a tonne for looking into it. You are doing a truly amazing work for all of us. Will close it now.
