### ISSUE TITLE
Local File Scan not recursive

### ISSUE THREAD

**Issue by Viper911** [gibaBR/Switch-Backup-Manager#117]
Running 1.2.1 and when I pick root folder using eshop tab it will go through all sub folders and find everything.  When I do the same on Local Files it seems like it goes goes the first folder then stops.  If I pick the next folder as the starting point it work on that one and so forth (i.e. its finding the files).  In any case seems like local tab it not going through all folders and only looking at the first one.

**Comment by Viper911** [comment]
More info.  Looks like its trying

2019-01-04 06:46:32.163 [INFO]    Adding 251 files to local XCI database
 then adds about 5 of them , then gets this error

2019-01-04 06:46:43.237 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Switch_Backup_Manager.Util.GetFileData(String filepath)
   at Switch_Backup_Manager.Util.AddFilesFromFolder(String path, String fileType)

**Comment by Viper911** [comment]
Also is there a way to know which file its getting hung up on.  The error message doesn't give much info

**Comment by garoxas** [comment]
> Also is there a way to know which file its getting hung up on. The error message doesn't give much info

try open command prompt on the folder and do `dir *.xci` or `dir /od /tc *.xci`
the app lists files based on its creation date, so we need to use above command to sort the files from the oldest to newest
and since you said it stops adding files after 5, you can narrow it down and try add either the 5th or 6th file from the list and see which one causing the issue, and report back here

**Comment by Viper911** [comment]
Finalaly made it through all the bad ones.  Here is the list.

[cid:image001.png@01D4A4C1.154B3240]

________________________________

**Comment by garoxas** [comment]
> 
> Finalaly made it through all the bad ones. Here is the list. [cid:image001.png@01D4A4C1.154B3240]
> […](#)

can you reattach the image. it shows nothing for me
would be helpful if you can give all the details (game name, file size, scene release or converted xci)
thanks

**Comment by Viper911** [comment]
Attached

![capture](https://user-images.githubusercontent.com/3239145/50724781-5655c800-10b8-11e9-814e-aa58db7ef5f0.JPG)

**Comment by Viper911** [comment]
Not sure on the Scene part, but were all xci files before I renamed to .bad to get the manager to skip the file.

**Comment by garoxas** [comment]
thank you, and judging by the file names I'm assuming they're custom XCI and it's already a known issue (see #104)
and since I don't have any, I can't help you with that. sorry 😞

**Comment by garoxas** [comment]
can you try this and let me know the result
https://mega.nz/#!FcVxFAzQ!IqsuKzFFbvtP0euQwHPyMBRW0fs1NsAPb3hmNHvTD7s

also please check the log (use the actual sbm.log file, not the one in the app) and see if there's this error message `Fatal error. This should not happen`

**Comment by Viper911** [comment]
Works now.  I put all the “bad” files in a folder and added a few file by file as well as imported the whole folder.   No errors and all come in.  I am running the full scan now to make sure all the original files that worked also still come in.  Is this a new build?  Still shows 1.2.1?

In any case, should I just use this version now?

BTW, the consistent thing that seems to be with these files (that were “bad”) is they are trimmed where none of the ones that originally worked were not.

Mark


________________________________

**Comment by garoxas** [comment]
> 
> Works now. I put all the “bad” files in a folder and added a few file by file as well as imported the whole folder. No errors and all come in. I am running the full scan now to make sure all the original files that worked also still come in.

great

> 
> Is this a new build? Still shows 1.2.1?

this is not an official release. just something I built with some fixes for you to test since I don't have those XCI files
later I'll submit a PR so it can be merged to the main repository as official release

> 
> In any case, should I just use this version now?

the changes are minimal, so it's fine if you want to use this until the next version release

> 
> BTW, the consistent thing that seems to be with these files (that were “bad”) is they are trimmed where none of the ones that originally worked were not. Mark
> […](#)

trimmed file should not be an issue. it's because they're custom XCI and since it's relatively new thing, this app is not properly tested to handle those files
