### ISSUE TITLE
Miss some backups during detection of folder

### ISSUE THREAD

**Issue by DavidBabel** [gibaBR/Switch-Backup-Manager#12]
Average is 1 on 2.

Other backups are ignored. Making the soft quite useless.

**Comment by gibaBR** [comment]
Pleasy try again on version 1.0.6 and report back. If errer persists, put your log file here.

**Comment by DavidBabel** [comment]
it crashes : https://gist.github.com/DavidBabel/6ccb201f184014778571e51be6254846

**Comment by gibaBR** [comment]
I should work now.
