### ISSUE TITLE
Compatibility with newer nsps?

### ISSUE THREAD

**Issue by eikowagenknecht** [gibaBR/Switch-Backup-Manager#127]
Seems like the tool can not handle newer .nsps (firmware version 7?). It does not show details like "Game revision", "Masterkey revision" etc. for those files. Also renaming those files does not work either. Is there a way to fix this?

**Comment by garoxas** [comment]
do you have master_key_07 on your keys.txt?
some games (Grand Prix Story) is broken on the latest release, you can try the unofficial build by me if you want https://mega.nz/#!1MlTjIRR!LBgy41jpGqhxB4riYwdg-CVtg7cb3hdC2FsanTBr9D8, or build yourself from my PR

**Comment by eikowagenknecht** [comment]
Thanks for the reply. I built using your PR, but it did not work unfortunately. I guess it must be the master_key_07 then, but I don't know where to get that..

**Comment by garoxas** [comment]
if you list the games that don't work, I can try find out whether they indeed require master key 7 or it's issue with the app itself
you can use Lockpick to get master key 7 (only if you're updated to FW 7 or up) or search it on google

**Comment by deadair3210** [comment]
Not sure if this is too late, but I think I have figured out what is causing the app to ignore the key. I had to make the key all UPPERCASE before the app would even acknowledge it existed
