### ISSUE TITLE
Local files not visible

### ISSUE THREAD

**Issue by smee2018** [gibaBR/Switch-Backup-Manager#128]
folder under root with files in (EG c:\1) doesn't show in local files. Will show under e-shop but not local.

NSP or XCI files not seen locally :(

V1.2.1 as well as older versions, tried on 2 systems with different file

**Comment by garoxas** [comment]
what did you mean by it'll show up under e-shop tab but NSP not seen locally?
NSP will always show up on e-shop tab, while local tab is only for XCI
I've tested put my games on Z: root and have no issue

**Comment by smee2018** [comment]
In that case it's user error as I didn't know the local tab is only for XCI! 

My bad - sorry!! Thanks for a great app, really useful :)

**Comment by garoxas** [comment]
no problem 😄 
I think you can close this issue
