### ISSUE TITLE
Trouble renaming

### ISSUE THREAD

**Issue by Sovikos** [gibaBR/Switch-Backup-Manager#143]
Why is it some NSP files don't get their Game Titles? It will just take the file name with the titleid and whatever else, and put it in the Game Title.  Then when autorenaming will add the Title ID again to the file name.  My keys.txt are up to date I think.  Not sure if this is a titlekeys.txt issue or what it is.

**Comment by deadair3210** [comment]
Are the nsp files damaged, maybe missing cmnt or meta?

**Comment by Sovikos** [comment]
I am not sure.  What do I use to check?

**Comment by garoxas** [comment]
this issue has been resolved in the gbatemp right?
only need to use the latest build from source code instead of the official 1.2.1 release

@gibaBR I think it's safe to close this issue

**Comment by gibaBR** [comment]
Thank you @garoxas
