### ISSUE TITLE
Is there any way to test if a cert is banned?

### ISSUE THREAD

**Issue by deadair3210** [gibaBR/Switch-Backup-Manager#144]
I know this isnt exactly related, but I have two different certs from two different switches and both are stating that they are banned. Is there any way to test them to make sure its not a issue with the program?

**Comment by garoxas** [comment]
if the app says it's banned then the certificate is definitely banned
if that's not enough you can try access eshop on the device itself and see how it goes
other way to test it is by manually make a request to any nintendo server using the certificate, if it returns 403 Forbidden then it's banned (although proceed with extra caution, you could end up flagging a clean certificate and make it banned if you make a wrong request)

**Comment by deadair3210** [comment]
Ok wasn't sure and wanted to check, the certs are banned since the people who owned the switchs before me weren't the most concerned with staying unbanned

**Comment by deadair3210** [comment]
What is the recommended way to extract the cert from my switch, just to make sure I did it correctly. Friend bought a new switch and I modded it immediately after he took it out of the box and the program still claims that the cert is banned

**Comment by garoxas** [comment]
No don't do that. I'm not even sure that the version update thing still works seeing that even reswitched discord no longer has versionlist updated
Gonna make a few changes in the app soon so it won't connect directly to N server anymore

**Comment by deadair3210** [comment]
Ok, will wait, let me know if you need anything tested. Hope I didn't get my certs banned lol

**Comment by garoxas** [comment]
> Hope I didn't get my certs banned lol

Yeah I'm very sorry if that happens ☹️
No one has ever reported this before so I was assuming it still works and only because my cert was busted. But on the other hand Reswitched discord still hasn't update their version list, so I have suspicion that there's indeed something changed in N server
I've added a confirmation dialog in the app with warning `Updating directly from Nintendo may no longer work and may get your certificate banned` for users who still wish to try connecting directly to N server, but until I can get confirmation that indeed it's no longer works then I'll keep the feature in the app (hopefully without keep burning other people certificates 🤞 )

**Comment by garoxas** [comment]
Screw it. I'll just believe what you said that certificate from brand new switch also doesn't work, so now I've removed everything so the app will only download from Pastebin and not N server

**Comment by deadair3210** [comment]
Is there any way people can help keep the pastebin up to date if we know there is a later update?

**Comment by garoxas** [comment]
If you have the latest version list, send it to me so I can update the Pastebin

**Comment by deadair3210** [comment]
Latest I have is the current list that the app pulls from pastebin, but I know that it is out of date since I have updates that it states dont exist

**Comment by deadair3210** [comment]
Might be able to scrape the tinfoil website for the latest update numbers, though that would be a bit sketchy

**Comment by garoxas** [comment]
No. I prefer a more reliable method. Something that pulls directly from N server if much more preferred

**Comment by deadair3210** [comment]
Don't blame you, hope you find something, the app is very useful for keeping up with a collection
