### ISSUE TITLE
Wrong game title 

### ISSUE THREAD

**Issue by FinnYoung** [gibaBR/Switch-Backup-Manager#16]
0100C4E004406000

Game title saying: "Cartoon Network Adventure Time: Pirates of the Enchiridion"

**Comment by gibaBR** [comment]
What's the problem?

**Comment by FinnYoung** [comment]
expected game title: "Adventure Time: Pirates of the Enchiridion"
actual game title: "Cartoon Network Adventure Time: Pirates of the Enchiridion"
searching for "Adventure Time: Pirates of the Enchiridion" i can't find any mention of "Cartoon Network". i believe it's a bug

**Comment by gibaBR** [comment]
Thais mame os retrieved from The cartridge image itself. On version 1.0.7
it comes from scene data base. Search for the title ID.

Em dom, 22 de jul de 2018 18:04, Finn Young <notifications@github.com>
escreveu:

**Comment by FinnYoung** [comment]
any way to contact guys running scene database and ask them to fix it?

BigBlueBox added 'Cartoon Network' to beginning of game title. SiMPLEX rip provided without that
wiki doesn't mention 'Cartoon Network' either: http://adventuretime.wikia.com/wiki/Adventure_Time:_Pirates_of_the_Enchiridion
https://en.wikipedia.org/wiki/Adventure_Time#Video_games

nintendo off site is ok too: https://www.nintendo.com/games/detail/adventure-time-pirates-of-the-enchiridion-switch

**Comment by FinnYoung** [comment]
i hate that too, but mb it worth to add custom logic where 'Cartoon Network ' will be dropped for 0100C4E004406000. no matter from where this information taken it's still a wrong title

**Comment by gibaBR** [comment]
But as I said to you, that name was on the image of The cartridge itself. I
can't do anything a out that, sorry...

Em dom, 22 de jul de 2018 18:45, Finn Young <notifications@github.com>
escreveu:
