### ISSUE TITLE
App does not finish opening XCZ

### ISSUE THREAD

**Issue by garoxas** [gibaBR/Switch-Backup-Manager#160]
Follow-up from discussion at #157, the app will stuck in infinite loop when opening some XCZ
Some of the reported titles
- 0100BB1009E50000
- 0100FE500D0CA000
- 01000320000CC000

@gibaBR I've reproduced it with Captain Toad title, and as you said it stuck at line 3227
I've temporary fixed it by changing said line to line below but it's hacky. Gonna take a look further later when I get time to find a proper fix
`
while ((num4 = fileStream.ReadByte()) > 0 && num4 > 0)
`

**Comment by garoxas** [comment]
It looks like there's a discrepancy between file offset in HFS header and the actual file offset, causing in some files with better compression to attempt to read beyond the file length
My previous "hacky" solution may still be needed as precaution

@gibaBR 
Please check my commit above. If you're okay with it, I'll make a PR
Couldn't find any better solution than to abort the process when stream offset exceed file length. It works on my tests but you may need to test with yours too

**Comment by gibaBR** [comment]
Gonna take a look! Thank you!

Em dom, 24 de nov de 2019 13:11, Garoxas <notifications@github.com>
escreveu:

**Comment by gibaBR** [comment]
Its seems to work. Bad news is SMB thinks all .XCZ files are not trimmed.
I'll work on this.
Thank you one more time, @garoxas


---
Gilberto Júnior
http://raspberrybrasil.blogspot.com.br/
http://www.flickr.com/photos/gibajr/

**Comment by garoxas** [comment]
Yes I've noticed that too. Maybe later I'll take a look at that

**Comment by gibaBR** [comment]
It's solved :)
---
Gilberto Júnior
http://raspberrybrasil.blogspot.com.br/
http://www.flickr.com/photos/gibajr/
