### ISSUE TITLE
sync titles from directory/directories

### ISSUE THREAD

**Issue by FinnYoung** [gibaBR/Switch-Backup-Manager#18]
it's related to https://github.com/gibaBR/Switch-Backup-Manager/issues/7

i propose to add setting 'folder(s)' and specify there directory/directories where backups located (instead of manually adding files/folders).
i saw similar functionality in dolphin emulator (in its own titles manager) and it was awesome
i believe that most users store their backups in a single (in worst case scenario in a few) directories. in case if i add few backups it's a pain in a neck to manually add them into application library. i just want to refresh database and see new titles there.

for me it's one of most important features. i searched for it and hoped to see it in first releases

from implementation point of view i don't think it will be harder compared to what application doing now

**Comment by gibaBR** [comment]
It was implemented on 1.0.8
