### ISSUE TITLE
Does not rename to correct CDN filename

### ISSUE THREAD

**Issue by cryptolute** [gibaBR/Switch-Backup-Manager#22]
After running batch rename on some NSP's, I (to my great sadness) discovered it does not name them correctly. I use the term "correctly" towards what the files would be if grabbed with CDNSP.

Using fortnite as an example, original filename as downloaded is -

Fortnite [010025400aece000][v0].nsp

Here is what it renamed to via your switch backup manager -

Fortnite [v0].nsp

This behavior would definitely be appreciated towards those who are using older nsp installers that require maximum name length to be under 59 characters (devmenu), but for everyone else using updated software the filename length is no longer a issue.

Instead, what will happen now is that when one goes to sync their NSP folder via CDN, it will now re-download all of the switch backup manager renamed files due to titleid being removed from the name.

Is there a easy way to fix this, or at least give us a toggle option to preserve titleid exactly as it would come from CDNSP?

Thank you!

**Comment by gibaBR** [comment]
You can go to options menu and make a custom renaming pattern

Em ter, 31 de jul de 2018 18:27, crypt <notifications@github.com> escreveu:

**Comment by cryptolute** [comment]
Thank you so much for the quick reply! I did not even know that option was there! After playing a little bit, it still does not create the desired output requested as above. For example...

{gamename}{titleid} outputs as Fortnite [v0]010025400AECE000.nsp

It appears the [v0] is considered part of the gamename to switch backup manager? is it possible to decouple this? And is it also possible to add some options with brackets? For example, {titleidbrackets} would output [010025400AECE000] instead of just 010025400AECE000

I thought perhaps "revision" was what I was looking for, but it appears not to be. Is it possible to add a {version} option that would designate [v0], [v65555] etc?

To have SBM auto-rename files correctly formatted to CDNSP format, it would essentially be

{gamename}{titleidbrackets}{version}

assuming that gamename gets the version decoupled and you allow for a titleidbrackets + version (with brackets, so [v0] etc

Does that make sense?

PS - Thank you, GREAT application!!!

**Comment by gibaBR** [comment]
Yes, you are correct. I'll do this for sure and release until the end of
the week.

Em ter, 31 de jul de 2018 18:58, crypt <notifications@github.com> escreveu:

**Comment by gibaBR** [comment]
Available on v 1.0.9
