### ISSUE TITLE
Speed up NSP extraction

### ISSUE THREAD

**Issue by garoxas** [gibaBR/Switch-Backup-Manager#23]
I noticed that the NSP reading is slow because you called hactool to extract every single NSP files only to be able to read the content of XML files in them (https://github.com/gibaBR/Switch-Backup-Manager/blob/master/Switch%20Backup%20Manager/Util.cs#L1305)

So I've made a simple Python script that able to read the XML file in an NSP (or export it as a file) so you can save some time wasted extracting all the other files
https://gist.github.com/garoxas/b41b7acca5c4c833fe446c22951cf005

Tested by extracting XML from 51 NSP files totalling 13.9GB which only took 4.690s
If you are interested and need to port it to C#, just let me know so I can assist you with that

**Comment by gibaBR** [comment]
Thank you very much! 
Actually, the XML is only one of the files we need. I use the XML to get the name of the nsp file that contains other info, so I need to extract that file too. StudentBlake used a modified version of nstool to extract just the smaller nsp files, so it is super fast now. I'm finishing other things and will release this new version until the end of the week. But maybe your solution is faster, I don't know. Could you look at my code and see if it could fit there?

**Comment by garoxas** [comment]
Sure, I see that you've released the new version with nstoolmod
I will test it tomorrow and compare the speed between this and using my script

**Comment by garoxas** [comment]
So apparently your code still expecting other files other than the XML, as the line https://github.com/gibaBR/Switch-Backup-Manager/blob/master/Switch%20Backup%20Manager/Util.cs#L1376 trying to open an NCA file as well
However based on the XML reading speed alone, I don't think that my script has that much better performance than the one already working on 1.0.9 with nstoolmod. So I guess better we'd leave it as it is and use the one that already working instead (it's already quite fast right now though)

Closing this right now. Thanks

**Comment by gibaBR** [comment]
Thank YOU.

---
Gilberto Júnior
http://raspberrybrasil.blogspot.com.br/
http://www.flickr.com/photos/gibajr/

**Comment by gibaBR** [comment]
This guy just solved my problems with nstoolmod.exe!
