### ISSUE TITLE
Auto renaming problem

### ISSUE THREAD

**Issue by Snake87r** [gibaBR/Switch-Backup-Manager#32]
Hello,
there is a problem with autorenaming, I've tried this settings:
{sceneid} - {gamename} ({region} v{revision}) ({languages}) [{developer}]

and this is the result:
1 - The Legend of Zelda Breath of the Wild (WLD v1.0.0) (en,fr,de,it,es,ru,ja) [Nintendo].xci

but i've expected three 0 before the 1:

0001 - The Legend of Zelda Breath of the Wild (WLD v1.0.0) (en,fr,de,it,es,ru,ja) [Nintendo].xci

It's possible to modify {sceneid}?

Thanks.

**Comment by gibaBR** [comment]
You're right! Problem solved and will be available on version 1.1.1
