### ISSUE TITLE
Issue witch manual scrape.

### ISSUE THREAD

**Issue by astanix** [gibaBR/Switch-Backup-Manager#38]
Selecting scrape info from web under tools causes an unhandled exception.

**Comment by chronoss09** [comment]
![bad97bdac620be7c2ca90e72388c3da3](https://user-images.githubusercontent.com/17669980/44000763-98cb1f0e-9e1d-11e8-9e8b-d77805a5c174.png)

**Comment by gibaBR** [comment]
Fixed. scheduled for next release.
