### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by FinnYoung** [gibaBR/Switch-Backup-Manager#4]
OS: Windows 10 Pro

Steps to reproduce:
1) Go to "Display Settings" and set scale to 200%
2) Open backup manager
3) Local files -> Add

Expected to have window the same size as previously
Actual result: Scale in application reset to 100% and everything looks very small

**Comment by gibaBR** [comment]
Could not completly reproduce the problem, but researching from the internet I might have found the solution and it will be on the next release. I'm going to close the issue and if the problem still happens, please re-open the issue.

**Comment by FinnYoung** [comment]
but still exist. these screenshots taken on 1.0.9
https://imgur.com/a/lQcaA5S

**Comment by FinnYoung** [comment]
the same bug happen when i try to set a folder to scan on startup
