### ISSUE TITLE
Application crash when i try to import games having "Sonic Mania Plus"

### ISSUE THREAD

**Issue by FinnYoung** [gibaBR/Switch-Backup-Manager#5]
Steps to reproduce:
1) Having empty library open application
2) Add Files/Folder (it should include Sonic Mania Plus from (LiGHTFORCE). Filename: lfc-abd7c.xci)
Expected result: See some titles in a list
Actual result: Application automatically closes without any exceptions/errors

**Comment by gibaBR** [comment]
Yes, the problem occurs with this release. I will filter this on next release, so the application will ignore it, for now, until this problem is solved.

**Comment by FinnYoung** [comment]
Now application ignore not only this file, but all files going after that.
If i try to import folder all titles going after "Sonic Mania Plus" skipped.

**Comment by gibaBR** [comment]
OK, I think I found the problem. Updated the code. Download v1.0.4 again.

**Comment by FinnYoung** [comment]
Woks fine now. Sonic mania imported successfully.
