### ISSUE TITLE
Request for AutoRename: Alternative CDNSP Format or New Custom Field

### ISSUE THREAD

**Issue by ozayturay** [gibaBR/Switch-Backup-Manager#51]
When renaming DLC NSP's with CDNSP pattern [DLC] is put in the beginning of the file unlike [UPD] which is put after the game name which is more sensible. I guess it is because CDNSP renames DLC's like this but an alternative CDNSP pattern or a variable like {nsptype} which gets values BASE, UPD, DLC according to the NSP type can be a good enchancement for OCD person like me. :)

Also when automatically putting title id with {titleid} an option to use lowercase letters or an alternative variable like {titleidlower} is again can be a good enchancement. ;)

**Comment by F3Speech** [comment]
{nsptype} substituting "","[UPD]","[DLC]" would be a massive help.
I can't really use renaming without it.

**Comment by deadair3210** [comment]
Agreed

**Comment by garoxas** [comment]
try this https://mega.nz/#!8EtR3Q5D!vn5P32igzG3eqMwvdtHT3ge3FGgGgSdrm-rs7L58I6U for {nsptype} support

**Comment by gibaBR** [comment]
Done by @garoxas  #129
