### ISSUE TITLE
Certain Dumps Not Importing Correctly

### ISSUE THREAD

**Issue by Tafty1987** [gibaBR/Switch-Backup-Manager#55]
I'm not sure where this problem lies but importing certain games cause's switch backup manager to read the wrong Title ID. I will use axiom verge as my example.

if you take a look at the scene release the title ID for the game is 0100052004384000, but when I import my XCI of the game it gives me the title ID of 0100B1F00660E000(in switch backup manager)

now at first, I presumed this may be because of a bad dump but when using XCI Reader it confirms that the title id Is in fact 0100052004384000

Monster Hunter Ultimate doesn't import correctly either but that is because it's missing the 0 at the start of the titleID on the nswdb. i have reported that error to them

**Comment by Tafty1987** [comment]
Monster Hunter has now been corrected on the nswdb

**Comment by garoxas** [comment]
it's nswdb's mistake
0100052004384000  is for the eshop version, see here http://switchbrew.org/index.php/Title_list/Games

XCI Reader does not actually read the information from XCI file
it only compares crc32 with nswdb and return the one matching with it. so it's always showing whatever Title ID nswdb has

**Comment by Tafty1987** [comment]
feel free to mark this as fixed, i have spoke with nswdb and got them to fix the titleID, axiom will now work correctly in the software

**Comment by gibaBR** [comment]
Thank you. I think you can close the issue.

Em sáb, 15 de set de 2018 16:37, Tafty1987 <notifications@github.com>
escreveu:
