### ISSUE TITLE
.nsp support?

### ISSUE THREAD

**Issue by FinnYoung** [gibaBR/Switch-Backup-Manager#6]
Will be good to have .nsp support with rename functionality and to see things in library

**Comment by vris2809** [comment]
When you can doìt in a new database, that we can change between xci and nsp.
Great Work

**Comment by chronoss09** [comment]
Great thing for .nsp file, i'm waiting for also !

**Comment by Icedtouch** [comment]
It will be great

**Comment by gibaBR** [comment]
Supported on v1.0.6. Renaming is still not enabled

**Comment by Devilb0y** [comment]
actuallu doesnt work, it shows msg "Done", but nothing happend :(

**Comment by vris2809** [comment]
Great Work, nsp files working fine

**Comment by Devilb0y** [comment]
2018-07-22 16:17:12.592 [INFO]    Adding 1 files on local Eshop database.
2018-07-22 16:17:12.639 [INFO]    Adding NSP file: Hollow [0100f210061e8000][v0]
2018-07-22 16:17:12.731 [INFO]    Extracting NSP file.
2018-07-22 16:17:14.453 [ERROR]   Directory tmp was not created ?!
2018-07-22 16:17:15.007 [ERROR]      в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileSystemEnumerableIterator`1.CommonInit()
   в System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   в System.IO.Directory.GetFiles(String path, String searchPattern)
   в Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-07-22 16:17:15.772 [ERROR]      в System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   в Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-07-22 16:17:16.040 [ERROR]      в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   в System.IO.Directory.Delete(String path, Boolean recursive)
   в Switch_Backup_Manager.Util.GetFileDataNSP(String file)
   в Switch_Backup_Manager.Util.AddFiles(String[] files, String fileType)

**Comment by gibaBR** [comment]
This happened to mee sometimes and I could not find what was causing that. Solution was to restart computer. Can you try it?

**Comment by Devilb0y** [comment]
tryed, but nothing change

**Comment by FinnYoung** [comment]
i will not be able to check it in closest ~10 hours, but mb it happens because of having the same title in 
.nsp and .xci formats?
just a guess after reading: `[ERROR] TitleID is already on database`

**Comment by Devilb0y** [comment]
nope, .xci section is empty also i added titles that dont have retail release, eshop only, so there are no xci for any of them

**Comment by FinnYoung** [comment]
doesn't work for me either. i added a folder, but no nsp titles appeared in 'local files'

**Comment by FinnYoung** [comment]
it's not because of that. my username uses only Latin letters
and i have no cyrillic symbols in app/games paths
win10pro with latest updates

**Comment by vris2809** [comment]
possibility of sorting change date

**Comment by Devilb0y** [comment]
just renamed my username from cyryllic to latin and it works now, maybe problem in hactool or dll's ?
