### ISSUE TITLE
[REQUEST] Install NSP files directly to microSD

### ISSUE THREAD

**Issue by cattivik66** [gibaBR/Switch-Backup-Manager#68]
Hi!
I think that it would be nice to be possible to install nsp files directly to the microSD.
This becouse:
- it would be much faster than installing from the Switch. On the switch I get about 15Mb/sec with tinfoil, with the PC I reach 95mb/sec when writing the NSP.
- no worries about space left in the microsd, and deleting old nsp from the switch

I'm not 100% sure if that would be possible, but I was thinking at this workflow:
1. check if the space is enought. If the NSP is a patch, and in the microSD there is already a patch, the software should check the size of the old patch as it would be removed before proceed. If the space is not enough show a warning.
2. make a procedure that unpacks the NSP to separated files in a temp folder. This step would be required to be sure that the NSP does not have corrupted data. User should be able to choise a temp folder (or perhaps also just use the memory if enough to make everything faster?)
3. install them to the microSD. Also, if the NSP is a patch, check first for patches already installed and remove them to save some space.
4. at this point I think that the Switch would not accept the installed files on the microsd (or am I wrong?). If so, the software could create a new tiny nsp with only the few missing things required by tinfoil to register the software. I think it would be a very small nsp.
5. Finally, make the final step of registering the NSP files created at step 3.

This also opens to new future improvements, like bulk installation (user choises the nsp to install, and when he finishes he confirms the installation and the list of NSP).

**Comment by ericjwg** [comment]
it's not possible. even it is possible, u still need to extract the tik and install them to switch console.

**Comment by gibaBR** [comment]
Sorry @cattivik66, it can`t be done, as explained by @ericjwg
