### ISSUE TITLE
[Request]Delete old updates

### ISSUE THREAD

**Issue by 2g4y1** [gibaBR/Switch-Backup-Manager#71]
Hi,

would nice to have a feature to delete old update revisions when a newer one is present.

ps. you created a awesome backup manager =)

**Comment by gibaBR** [comment]
Thank you. I have done it. Will release soon.

Em qua, 26 de set de 2018 14:09, 2g4y1 <notifications@github.com> escreveu:

**Comment by 2g4y1** [comment]
Wow, that was quick =)
ty

**Comment by gibaBR** [comment]
:) It's ready for a week now. I Just need to test it a little more.

Em qua, 26 de set de 2018 14:13, 2g4y1 <notifications@github.com> escreveu:
