### ISSUE TITLE
Scraping games corruption issue.

### ISSUE THREAD

**Issue by Anunnymous** [gibaBR/Switch-Backup-Manager#72]
Whenever it's scraping your list of games, if it runs into a file that's corrupt (I'm not sure if it's actually corrupt, I'm just assuming) it quits scanning altogether. No error, doesn't freeze or close; just quits scanning and marks scan as done.

**Comment by garoxas** [comment]
uh to clarify, I didn't fix this. I mistype the issue number in commit https://github.com/gibaBR/Switch-Backup-Manager/commit/eeb486aff9174e013ed62e8689ab32687b1929e7, it supposed to say #73 . sorry
