### ISSUE TITLE
Crash on startup with v1.1.9

### ISSUE THREAD

**Issue by Bauxite** [gibaBR/Switch-Backup-Manager#84]
Version 1.1.9 is crashing silently on startup on Windows 10 x64, whether run as a fresh install or an in-place upgrade over working 1.1.8 folder.

Built from current source and copied the new executable over the .exe from the release zip and everything works as expected.

From Windows Event Viewer:

> The process was terminated due to an unhandled exception.
>
> Exception Info: System.IO.FileLoadException
>    at Switch_Backup_Manager.FrmMain..ctor()
>    at Switch_Backup_Manager.Program.Main()

**Comment by vris2809** [comment]
have the same problem on Win10/64, 1.1.9 will not start

**Comment by gibaBR** [comment]
Ok guys, gonna take a look

Em dom, 4 de nov de 2018 08:46, vris2809 <notifications@github.com escreveu:

**Comment by gibaBR** [comment]
Sorry about that. I just uploaded the correct files now. 
Please, download it again and report back if possible.

**Comment by vris2809** [comment]
Now it´s working fine for me, thanks gibaBR

**Comment by Bauxite** [comment]
Resolved, thanks!
