### ISSUE TITLE
Missing Content Type in Custom pattern of NSP

### ISSUE THREAD

**Issue by LiloBzH** [gibaBR/Switch-Backup-Manager#85]
Hi

Can you add, please, CONTENT TYPE in custom pattern of NSP section ?

Thank's !

**Comment by adh1310** [comment]
+1 on this. Maybe allow the usage of the "Game title" in the rename options, since it includes the content type?

**Comment by gibaBR** [comment]
It'll be on next version!

**Comment by gibaBR** [comment]
done

**Comment by LiloBzH** [comment]
good news. Thank's :)
